command: hugo --gc --minify -b $URL
commandOrigin: config
environment:
- HUGO_VERSION
- HUGO_ENABLEGITINFO
- HUGO_ENV
publish: /opt/build/repo/public
publishOrigin: config
plugins:
- inputs:
ebug: true
